### ISSUE TITLE
Show overlapping letters

### ISSUE THREAD

**Issue by Zena-park** [tokamak-network/Tms-frontend#16]
**Describe the bug**
Token balance letters are displayed overlapping other letters.

**Screenshots**
 
<img width="837" alt="스크린샷 2024-07-18 오후 2 17 21" src="https://github.com/user-attachments/assets/b1588a05-e05c-4b5f-a57b-4f90c9956670">

**Comment by Shivansh070707** [comment]
pls check now

**Comment by Shivansh070707** [comment]
pls check now

**Comment by Zena-park** [comment]
I checked it.
<img width="712" alt="스크린샷 2024-07-22 오후 4 33 27" src="https://github.com/user-attachments/assets/a72d3f19-84ea-40ef-8cc4-b74b3d24d4fd">
