### ISSUE TITLE
Allow unnecessary transfers

### ISSUE THREAD

**Issue by Zena-park** [tokamak-network/Tms-frontend#17]
**Describe the bug**
You can also send tokens to yourself.
Unnecessary token transfers only waste gas fees.
 
**Screenshots**
  
<img width="1021" alt="스크린샷 2024-07-18 오후 2 29 22" src="https://github.com/user-attachments/assets/5198cc8e-a184-4672-bc9a-3c042f71a91a">

**Comment by Shivansh070707** [comment]
Pls check now

**Comment by Zena-park** [comment]
I checked it.
