### ISSUE TITLE
Some issues and needs for improvement.

### ISSUE THREAD

**Issue by mandoopapa** [tokamak-network/Tms-frontend#19]
I'm very excited to see the work of the TMS project team in action. Here are some of the issues and improvements we would like to see. Please check them out.

1. It is possible to enter nothing in the Prepare step and Continue to the next step, after which none of the buttons will work.  And once you enter the Approve step, there is no way to go back.

Below is what it looks like when you enter Continue directly from the Prepare step.
![image](https://github.com/user-attachments/assets/602a17ff-d9f5-4c5b-b558-9bec6176d000)

2. Even a very small CSV of 174 bytes won't upload, and none of the buttons will work unless you press X to exit.![image](https://github.com/user-attachments/assets/5f2462a0-3921-4da5-b547-c7518afb5d54)

If you submit another upload, you won't be able to upload another file, even if you cancel it with Cancel.
![image](https://github.com/user-attachments/assets/a791c55d-ba7e-4ff7-b80b-c08bc3b38c51)

**Comment by mandoopapa** [comment]
It asks me to search for the token name, but when I type the alphabet, it starts with invalid address. 
![image](https://github.com/user-attachments/assets/86c7cbf1-f9ae-4f44-b1e2-d22324c5e316)

**Comment by Shivansh070707** [comment]
pls check

**Comment by mandoopapa** [comment]
Thank you for your efforts to resolve the issue.

The first issue was that it would let us continue without any input, now it requires us to connect a wallet to proceed to the next step, so it seems like you've fixed it properly.

Regarding no.2, I've confirmed that TON, USDT, etc. are working fine, but wton, eth, etc. are still causing the same issue. Instead of making it inconvenient to check which tokens are being searched, how about showing the available tokens under the search field so that they can be selected with a click?


and after update, I got an issue for approve step.
![image](https://github.com/user-attachments/assets/daf90cc0-ac4f-40bf-a48b-a00d4debeacc)

there are two approve button, but above button doesn't work.

**Comment by Shivansh070707** [comment]
For the second part we are planning to add it later as it will need some UI
design

**Comment by Shivansh070707** [comment]
pls check now'

**Comment by mandoopapa** [comment]
Thank you!
