### ISSUE TITLE
Unnecessary approval request

### ISSUE THREAD

**Issue by Zena-park** [tokamak-network/Tms-frontend#20]
**Describe the bug**
It has already been approved to the maximum.
We are also requesting approval.

**Screenshots**
1. Approve Unlimited Amount
<img width="906" alt="스크린샷 2024-07-18 오후 2 33 08" src="https://github.com/user-attachments/assets/330aff2d-3cd8-480d-871a-2a5d45644f0e">

2. multi send 
<img width="1057" alt="스크린샷 2024-07-18 오후 2 33 20" src="https://github.com/user-attachments/assets/ace18d7b-0963-45b3-bfa5-121c4248b5af">

3. finish transferring 
<img width="1017" alt="스크린샷 2024-07-18 오후 2 33 45" src="https://github.com/user-attachments/assets/017ccdbe-5393-4943-bdd0-2c6ba99a34d6">

4. **You are also requesting approval again.**
<img width="1020" alt="스크린샷 2024-07-18 오후 2 35 07" src="https://github.com/user-attachments/assets/e9f9005c-57f7-4a23-89d7-6da32fcecacb">

**Comment by Shivansh070707** [comment]
can u check now

**Comment by Zena-park** [comment]
No response when pressing the multisend button.

<img width="850" alt="스크린샷 2024-07-22 오후 4 37 19" src="https://github.com/user-attachments/assets/9ff94da3-47a2-4e8b-a58b-a23ab4380aa7">

**Error MultoSending tokens: Execution reverted with reason: ERC20: transfer amount exceeds allowance.**

<img width="1382" alt="스크린샷 2024-07-22 오후 4 39 02" src="https://github.com/user-attachments/assets/5851f701-91ac-4923-920f-1f5e0d2acd0e">

**Comment by Shivansh070707** [comment]
its fixed now
