### ISSUE TITLE
Header is some different when it comes to the design

### ISSUE THREAD

**Issue by SonYoungsung** [tokamak-network/Tms-frontend#21]
**Issue description**
Global header for Tokamak Ecosystem looks really different than the original. 
You will be able to find and copy that header from their frontend repo. Or it'd be cool to make it as a react module through npm.

<img width="642" alt="image" src="https://github.com/user-attachments/assets/477d17e8-542c-43c1-9791-39c34c74abbb">
<img width="697" alt="image" src="https://github.com/user-attachments/assets/f52f88dd-21c1-444c-891b-7f633378b7bf">

**Comment by shivtokamak** [comment]
Can u share the repo , This one I made from scratch
