### ISSUE TITLE
Approve Exact Amount seem work strange

### ISSUE THREAD

**Issue by kooroot** [tokamak-network/Tms-frontend#22]
**Describe the bug**
When selecting Approve Exact Amount, the approve and cancel approve windows occur simultaneously.

<img width="1355" alt="스크린샷 2024-07-18 오후 2 18 40" src="https://github.com/user-attachments/assets/9e390505-a87b-4762-8eb5-1984788126ef">

<img width="417" alt="스크린샷 2024-07-18 오후 2 18 58" src="https://github.com/user-attachments/assets/d00b7a06-8d8d-407f-b698-495c3c71bd1e">

<img width="422" alt="스크린샷 2024-07-18 오후 2 19 25" src="https://github.com/user-attachments/assets/3f0f8a47-4597-40bf-b368-91f4e1d367a1">

**Comment by Shivansh070707** [comment]
pls check now
