### ISSUE TITLE
 There is no back button on the summary screen.

### ISSUE THREAD

**Issue by Zena-park** [tokamak-network/Tms-frontend#23]
**Describe the bug**
There is no back button.
If you notice a problem with 'Send Amount' on this screen, you may want to return to the previous screen.
 
**Screenshots**
 
<img width="817" alt="스크린샷 2024-07-18 오후 2 49 40" src="https://github.com/user-attachments/assets/09c0f9b5-8203-4a41-8d5c-b348b9c88ce8">

**Comment by Shivansh070707** [comment]
U need to click on Prepare to go back

**Comment by Zena-park** [comment]
When I click 'prepare', all the data I wrote will be lost. 
 
 - When I click 'prepare'
<img width="760" alt="스크린샷 2024-08-12 오후 2 11 11" src="https://github.com/user-attachments/assets/02bfad18-6158-4a1f-94e4-2a12a65690f6">

 - All the data I wrote will be lost
<img width="770" alt="스크린샷 2024-08-12 오후 2 11 19" src="https://github.com/user-attachments/assets/e15947ef-a461-42ff-ab12-3d30af5b8f69">

**Comment by Shivansh070707** [comment]
Pls check now

**Comment by Zena-park** [comment]
(1)  I filled out the transfer data after selecting the TOS token.
<img width="785" alt="스크린샷 2024-08-12 오후 11 08 45" src="https://github.com/user-attachments/assets/babf0c2f-7093-42a9-bb3a-6b56c311eeb4">

(2) After clicking the continue button on the screen above, I confirmed the information I entered.
<img width="784" alt="스크린샷 2024-08-12 오후 11 08 53" src="https://github.com/user-attachments/assets/5bac14d7-8bdd-4e23-a9be-ec89344089f7">

(3) After clicking the 'prepare' button on the screen above, you will see an edit screen for the information you entered.
      **`The selected token has disappeared.`**
<img width="759" alt="스크린샷 2024-08-12 오후 11 11 37" src="https://github.com/user-attachments/assets/e309e2cc-1314-49d5-8300-0a0c1df5d3c4">

(4)  After editing the transfer information, I clicked the ‘continue’ button.
<img width="774" alt="스크린샷 2024-08-12 오후 11 17 14" src="https://github.com/user-attachments/assets/24857eb7-c010-45c4-9fdc-8ff0f9489319">

(5) **`The asset being transferred has been changed to ETH`**. 
<img width="759" alt="스크린샷 2024-08-12 오후 11 17 21" src="https://github.com/user-attachments/assets/aaec270f-2078-4344-baa6-01227ed87dbe">

**Comment by Shivansh070707** [comment]
Yes because u didnt selected tos in second time
if u didnt select any assets then it will consider it as eth, This is the expected behaviour

**Comment by Zena-park** [comment]
I think the reason for the bug is that the token information I entered disappeared on screen 3 above.

**Comment by Shivansh070707** [comment]
Pls check now

**Comment by Zena-park** [comment]
The selected token(TOS) information in the Prepare click screen (2) below is not displayed on the screen.

- (1) Confirmation screen
![스크린샷 2024-08-15 오전 8 46 14](https://github.com/user-attachments/assets/531117de-9683-427f-9b4e-980410da3673)

- (2) When you click Prepare, the edit screen
![스크린샷 2024-08-15 오전 8 46 31](https://github.com/user-attachments/assets/b6540311-2c8b-4834-98fb-3bd7f3b2d658)

- (3) After clicking the 'continue' button, the confirmation screen
![스크린샷 2024-08-15 오전 8 46 45](https://github.com/user-attachments/assets/131a362f-55d6-4032-98fc-8ce3b4965a9a)

**Comment by Shivansh070707** [comment]
You need to select drop-down to get the details.

**Comment by Shruti92Shrivastava** [comment]
I think, It is good to select the token option again because if someone enters the wrong token and they want to change it, the drop down option will help in this case and they can easily change their token which they want to send.

**Comment by suahnkim** [comment]
@Shivansh070707 
1. we need to add option for ETH when drop down button is activated (see attached image)
<img width="459" alt="image" src="https://github.com/user-attachments/assets/00b78f35-8cac-4fb2-a434-89546c99dc35">

**Comment by suahnkim** [comment]
@Shivansh070707 
2. if the "search token name or address" field is empty -> [Continue] button should be disabled
<img width="761" alt="image" src="https://github.com/user-attachments/assets/547c3e6c-c789-4358-b2bb-7a0034b4d38e">

**Comment by suahnkim** [comment]
@Shivansh070707 
3. if a user clicks on "Prepare" during "Approve" step, you should repopulate the token on the "search token name or address" field that was previously chosen (do not leave it as empty) 
-> I noticed that you patched the frontend to use the previously chosen token as the token parameter -> which is good, but reflect that on the "search token name or address" field as well

**Comment by Shivansh070707** [comment]
Okay

**Comment by Shivansh070707** [comment]
Pls check now

**Comment by Zena-park** [comment]
When you select a token, it will be displayed as the token name, but the token symbol should be displayed.
(ex) TONStarter -> TOS
<img width="741" alt="스크린샷 2024-08-22 오전 10 23 34" src="https://github.com/user-attachments/assets/1105e7ad-5a45-49fb-8d3f-e941752f958d">

**Comment by Shivansh070707** [comment]
Pls check

**Comment by Zena-park** [comment]
> Pls check

I checked the token symbol is displayed.

**Comment by suahnkim** [comment]
@Shivansh070707 
Depending on how I interact with the frontend, I can still continue while token field is empty (see attached image)

<img width="728" alt="image" src="https://github.com/user-attachments/assets/69a9a8a5-322d-4412-b511-558165a49957">

**Comment by Shivansh070707** [comment]
if Input is empty  then that means we are sending eth instead of tokens

**Comment by suahnkim** [comment]
In the case I showed, it sends TOS token.

Anyways, it should be clear which token or eth is being sent. Not a good idea to leave it empty

**Comment by Shivansh070707** [comment]
okay instead of WETH I will replace it with ETH and if user didnt select anything from dropdpwn then he wont be able to click on the continue button , is that okay ?

**Comment by suahnkim** [comment]
I am not sure if I understand your comment about replacing weth with eth?

And yes, if the token is not selected, button should be deactivated

**Comment by Shivansh070707** [comment]
So in token drop-down I replaced wrapper ether with ethereum.

**Comment by suahnkim** [comment]
so, you won't show WETH? 

what is the reason?

**Comment by shivtokamak** [comment]
not sure tbh , I thought perople can directly send eth instead of wrapping and then sending

**Comment by suahnkim** [comment]
I think you can add the WETH option back, unless if you have a specific reason to remove it. 

other than that, the rest of the issue seems to be resolved

**Comment by shivtokamak** [comment]
Okay I Will add That

**Comment by shivtokamak** [comment]
Pls check now

**Comment by suahnkim** [comment]
@Zena-park I think this issue is fixed. Can you check and close the issue?

**Comment by Zena-park** [comment]
Okay! 
I will close the issue.
