### ISSUE TITLE
Footer and button images overlap

### ISSUE THREAD

**Issue by Zena-park** [tokamak-network/Tms-frontend#26]
**Describe the bug**
Footer and button images overlap

**Screenshots**
<img width="984" alt="스크린샷 2024-07-22 오후 4 35 16" src="https://github.com/user-attachments/assets/a95f576e-2bca-4bdc-b3cd-12dd09e8dd11">

**Comment by Shivansh070707** [comment]
Which device is this , not able to replicate the issue

**Comment by Zena-park** [comment]
PC , Chrome

**Comment by Shivansh070707** [comment]
pls check now

**Comment by Zena-park** [comment]
I checked it.
