### ISSUE TITLE
Standardize token name on the drop down menu

### ISSUE THREAD

**Issue by suahnkim** [tokamak-network/Tms-frontend#46]
Standardize token name on drop down option based on deployed token name (check explorer)

TON TON -> [**Tokamak Network** TON](https://explorer.titan.tokamak.network/token/0x7c6b91D9Be155A6Db01f749217d76fF02A7227F2/token-transfers)
TOS TOS -> [**TONStarter** TOS](https://explorer.titan.tokamak.network/token/0xD08a2917653d4E460893203471f0000826fb4034/token-transfers)
Wrapped Ethereum -> [Wrapped **Ether**](https://explorer.titan.tokamak.network/address/0x4200000000000000000000000000000000000006)
Tether USDT -> [**Tether USD** USDT](https://explorer.titan.tokamak.network/token/0x2aCC8EFEd68f07DEAaD37f57A189677fB5655B46/token-transfers)
<img width="458" alt="image" src="https://github.com/user-attachments/assets/98e0e122-83a3-45b0-8fc8-907794067147">

**Comment by suahnkim** [comment]
also, I would display the **token symbol** first and then the **name** 
ex: TON, Tokamak Network

**Comment by Shivansh070707** [comment]
pls check now

**Comment by suahnkim** [comment]
thanks @Shivansh070707
