### ISSUE TITLE
Execute Approve even if the transfer amount is insufficient

### ISSUE THREAD

**Issue by Zena-park** [tokamak-network/Tms-frontend#49]
When the amount I want to send is 100 USDC, my USDC balance is 0, the "Approve" button is activated.
If your balance is insufficient for the transfer amount, the "Approve" button should not be activated.

**Comment by shivtokamak** [comment]
So it should not go to step 2 if amount<sendAmount right ?

**Comment by Shivansh070707** [comment]
Pls check now

**Comment by Zena-park** [comment]
When the transfer amount is insufficient, the "Approve" button must be inactivated.
<img width="722" alt="스크린샷 2024-08-23 오후 6 24 01" src="https://github.com/user-attachments/assets/84118b24-1439-4f20-bcd0-3908f552f2c3">

**Comment by Shivansh070707** [comment]
<img width="1277" alt="image" src="https://github.com/user-attachments/assets/617a9d95-901a-4e5a-96af-57fb3230bc1f">
I added this popup so that user can know that they dont have enough balance

**Comment by suahnkim** [comment]
Instead of adding a popup it is a common UX to disable the button

**Comment by Shivansh070707** [comment]
I can disable it , should I remove the popup ??

**Comment by suahnkim** [comment]
Yeah, popup seems unnecessary

**Comment by shivtokamak** [comment]
please check

**Comment by Zena-park** [comment]
When the amount to send is greater than the amount held, the Continue button seems to be disabled, but there is no explanation.

<img width="779" alt="스크린샷 2024-08-28 오전 10 04 01" src="https://github.com/user-attachments/assets/5c9003df-a681-4803-a1d0-ac3b6afbf47f">

**Comment by shivtokamak** [comment]
Please check Now

**Comment by Zena-park** [comment]
I inputted the amount of balance shown on the screen, but the 'continue' button was not activated.

<img width="730" alt="스크린샷 2024-08-29 오전 8 09 39" src="https://github.com/user-attachments/assets/6f24e85f-f008-4511-8a50-8661223cfd8a">
 
<img width="728" alt="스크린샷 2024-08-29 오전 8 18 03" src="https://github.com/user-attachments/assets/0a2b033d-b6b7-4952-a519-5f48812ad086">

**Comment by shivtokamak** [comment]
This is because your tos balance is not exactly 3262.42 . It should be around 3262.18436 something. We are rounding off to 2 digits

**Comment by suahnkim** [comment]
this issue is not fixed. 
related to https://github.com/tokamak-network/Tms-frontend/issues/52#issuecomment-2326534957 issue. 

when displaying, you should not round UP -> you should cut off 
for example, if balance is 43.445, you should show 43.44, and not 43.45

**Comment by shivtokamak** [comment]
fixed in [commit ](https://github.com/tokamak-network/Tms-frontend/commit/7b1a4a900dc083b1160344520e1c72432e4eecb2) ,Please check

**Comment by Zena-park** [comment]
I checked. I will this issue.
