### ISSUE TITLE
I can continue to next step despite having insufficient balance

### ISSUE THREAD

**Issue by suahnkim** [tokamak-network/Tms-frontend#52]
<img width="729" alt="image" src="https://github.com/user-attachments/assets/3b549e4e-0fa8-4d19-a935-fd029c26d07a">

I have 0 TOS, and I have input to send 1 TOS 
But the Continue button is still active 

Correct behavior: 
1. shows message for insufficient balance
2. deactivate the continue button

OR 
1. After continue button is clicked, show the relevant warnings in the next step 

I recommend the implementing the former suggestion of deactivating the continue button

**Comment by shivtokamak** [comment]
This is fixed, please check

**Comment by suahnkim** [comment]
Can you also add the warning message for insufficient balance?

**Comment by Shivansh070707** [comment]
Sure

**Comment by suahnkim** [comment]
is this fixed?

**Comment by shivtokamak** [comment]
Yes Sir

**Comment by suahnkim** [comment]
insufficient balance condition is incorrect: 
I have 10 usdt, and I try to send 10 usdt -> it shows "Warning : Insufficient USDT balance for MultiSend" 

please double check the condition for this message.

<img width="761" alt="image" src="https://github.com/user-attachments/assets/62da784e-42f5-44de-9dfc-373a4dfa506d">

**Comment by shivtokamak** [comment]
Fixed in [https://github.com/shivtokamak/Tms-frontend/commit/4ddb86a6a7111e0aa715651873c24a5e080358f7](url)
