### ISSUE TITLE
Incorrect text for Approve option

### ISSUE THREAD

**Issue by suahnkim** [tokamak-network/Tms-frontend#53]
<img width="256" alt="image" src="https://github.com/user-attachments/assets/776281d2-8448-4168-bc00-910d376a2513">

For approve step, you provide 2 options 
1. Approve Exact Amount
2. Approve Unlimited Amount

However, "Approve Unlimited Amount" does not actually approve unlimited amount, it approves the max amount (or at least close to it -> i am guessing you approve the total.supply() of the token?)

please update the text to reflect this comment. 
Approve Unlimited Amount -> Approve Max Amount

**Comment by Shivansh070707** [comment]
approve max amount approves max uint256 , This is done intentionally so that users don't have to approve the tokens again

**Comment by suahnkim** [comment]
hey @Shivansh070707 
the issue raised here is not with the functionality, but with the name: 

Approve **Unlimited** Amount -> Approve **Max** Amount

"**Unlimited**" is incorrect term as the function approves to max value. If the user uses up the approve amount, they will need to approve again (it is not unlimited)

**Comment by shivtokamak** [comment]
This is done,please check
