### ISSUE TITLE
ETH amount display error

### ISSUE THREAD

**Issue by Zena-park** [tokamak-network/Tms-frontend#54]
The amount displayed in ETH appears to be incorrect.
![스크린샷 2024-09-04 오전 10 03 51](https://github.com/user-attachments/assets/4e028f2e-ba7c-4fed-9861-847cdb634a2b)

![스크린샷 2024-09-04 오전 10 07 44](https://github.com/user-attachments/assets/76087b53-3cc2-4794-94fb-03faf467e2aa)

**Comment by shivtokamak** [comment]
Done , Please check

**Comment by Zena-park** [comment]
There is only an ETH symbol next to the receipt address, without the amount to send.

<img width="696" alt="스크린샷 2024-09-08 오후 9 33 53" src="https://github.com/user-attachments/assets/134a26c6-4a0c-4c41-b49e-b68201f12eef">

**Comment by Shivansh070707** [comment]
Done , Please Check

**Comment by Zena-park** [comment]
I checked.
I will close this issue.
