### ISSUE TITLE
Unnecessary approval request 

### ISSUE THREAD

**Issue by Zena-park** [tokamak-network/Tms-frontend#55]
I already have an approved amount of 3261.415 TOS. 
However, the approval request screen is displayed again.

![스크린샷 2024-09-04 오전 10 10 26](https://github.com/user-attachments/assets/b25fcc02-ccda-4dcf-87fc-123da331ae21)

![스크린샷 2024-09-04 오전 10 10 43](https://github.com/user-attachments/assets/daf2803e-a3bd-42f4-b2af-b65573d35d3d)

**Comment by Zena-park** [comment]
If the allowance amount is less than the amount being sent, the approve radio button and the Multisend button will appear together, and clicking the Multisend button will result in an error.

> -------------- 
- The screen that the allowance amount is less than the amount being sent.
<img width="724" alt="스크린샷 2024-09-08 오후 9 41 12" src="https://github.com/user-attachments/assets/36a9304f-d693-4dca-be0d-861eceb17601">

> --------------
- The screen where the approve radio button and the Multisend button will appear together.
<img width="788" alt="스크린샷 2024-09-08 오후 9 41 22" src="https://github.com/user-attachments/assets/7c52af5d-6e5b-4501-951c-10a86216001f">

> -------------- 
- The screen that clicking the Multisend button will result in an error.
<img width="978" alt="스크린샷 2024-09-08 오후 9 42 44" src="https://github.com/user-attachments/assets/dc4413fe-10ab-4321-8c97-48957c0abcaf">

**Comment by Shivansh070707** [comment]
This is done , please check

**Comment by Zena-park** [comment]
When clicking the Multisend button will result in an error.

It seems that the allowance amount is less than the amount being sent. Please check [the test contents above](https://github.com/tokamak-network/Tms-frontend/issues/55#issuecomment-2336674783) again.

<img width="879" alt="스크린샷 2024-09-10 오전 9 58 40" src="https://github.com/user-attachments/assets/db3b80cd-5453-4c31-a276-97c1b24a8d05">

**Comment by Shivansh070707** [comment]
<img width="1274" alt="image" src="https://github.com/user-attachments/assets/0a139322-d8f5-4244-ad12-e22a2c11ad8e">
<img width="1279" alt="image" src="https://github.com/user-attachments/assets/18169c6d-d44b-4989-bf9c-3da82179e4e4">


can  u let me know how can I replicate this ? If we allow less amount then approve button is showing in my end

**Comment by Shivansh070707** [comment]
<img width="1280" alt="image" src="https://github.com/user-attachments/assets/aa162eaa-a85a-4c51-8198-054807abf6ae">
<img width="1254" alt="image" src="https://github.com/user-attachments/assets/569f62cc-c8c2-4cc7-938a-77385d574173">

**Comment by Zena-park** [comment]
I checked. 
I will close this issue.
