### ISSUE TITLE
Proposal to add space between the displayed amount and symbol

### ISSUE THREAD

**Issue by Zena-park** [tokamak-network/Tms-frontend#56]
It would be better if there was a space between the amount being sent and the token symbol.

`1.00USDC` -> `1.00 USDC `

![스크린샷 2024-09-04 오전 10 26 59](https://github.com/user-attachments/assets/b1016988-0ca4-4c64-8055-5a257906b9c3)

**Comment by shivtokamak** [comment]
Done , Please check

**Comment by Zena-park** [comment]
Confirmed.
I will close the issue.
