### ISSUE TITLE
Incorrect symbol display when selecting ETH

### ISSUE THREAD

**Issue by Zena-park** [tokamak-network/Tms-frontend#58]
I selected ETH as the asset, and on the sending screen, the WETH balance is displayed, and the symbol is WETH next to the amount being sent.
 
 > --------------------
 - The screen that I selected ETH as the asset.
<img width="735" alt="스크린샷 2024-09-08 오후 9 52 13" src="https://github.com/user-attachments/assets/fc34442e-dc9c-4f86-94fb-0cbbe48c76e4">

 > --------------------
 - the WETH balance is displayed, and the symbol is WETH next to the amount being sent
<img width="753" alt="스크린샷 2024-09-08 오후 9 52 22" src="https://github.com/user-attachments/assets/5d850696-0b76-4cfa-b328-fd86ce4ed546">

**Comment by Shivansh070707** [comment]
Done , Please check

**Comment by Zena-park** [comment]
I checked that it was fixed.
